# -*- coding: utf-8 -*-
"""Modul CUMI_MAP.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fwXc14KNBwCzyyELSrhUppOK61IstH1_
"""

# ============================================================
# CUMI-MAP | Step 1: Load Dataset dari File CSV
# ============================================================

from google.colab import files
import pandas as pd
import numpy as np

# Upload file CSV
print("Silakan pilih file CSV dataset...")
uploaded = files.upload()

# Baca file yang diupload
filename = list(uploaded.keys())[0]
df = pd.read_csv(filename)

# Validasi kolom yang dibutuhkan
KOLOM_WAJIB = [
    'latitude', 'longitude', 'jam_tangkap', 'fase_bulan',
    'suhu_permukaan', 'salinitas', 'kecepatan_arus', 'arah_arus',
    'klorofil_a', 'tinggi_gelombang', 'hasil_tangkapan_kg'
]

kolom_tidak_ada = [k for k in KOLOM_WAJIB if k not in df.columns]
if kolom_tidak_ada:
    print(f"\n⚠️  PERINGATAN — Kolom berikut tidak ditemukan:")
    for k in kolom_tidak_ada:
        print(f"   ✗ {k}")
    print(f"\nKolom yang tersedia di file kamu:")
    print(f"   {list(df.columns)}")
else:
    # Ambil hanya kolom yang dibutuhkan
    df = df[KOLOM_WAJIB].copy()

    print("=== CUMI-MAP Dataset ===")
    print(f"✓ File '{filename}' berhasil diload")
    print(f"  Total data: {len(df)} baris")
    print(f"\n--- 5 baris pertama ---")
    print(df.head())
    print(f"\n--- Info kolom ---")
    print(df.info())
    print(f"\n--- Statistik deskriptif ---")
    print(df.describe())

# ============================================================
# CUMI-MAP | Step 2: Preprocessing & Feature Engineering
# + Outlier Handling (Robust) — FIXED
#
# Perbaikan:
# 1. hasil_tangkapan_kg hanya di-clean, tidak di-scale (bukan fitur input)
# 2. IQR batas bawah di-floor ke 0 untuk fitur yang tidak mungkin negatif
# 3. Scaler di-fit HANYA pada train set → tidak ada data leakage
# ============================================================

import numpy as np
import pandas as pd
from sklearn.preprocessing import RobustScaler, MinMaxScaler
from sklearn.model_selection import train_test_split

df_clean = df.copy()

print("=== Missing Values ===")
print(df_clean.isnull().sum())

# ── LAYER 1: Filter nilai tidak mungkin secara sains ─────────
BATAS_FISIK = {
    'suhu_permukaan':     (25.0, 33.0),
    'salinitas':          (30.0, 37.0),
    'kecepatan_arus':     (0.0,  2.0),
    'klorofil_a':         (0.0,  5.0),
    'tinggi_gelombang':   (0.0,  4.0),
    'hasil_tangkapan_kg': (0.0,  20.0),  # di-clean tapi tidak di-scale
    'latitude':           (-5.5, -4.5),
    'longitude':          (118.5, 120.5),
}

print("\n=== LAYER 1: Filter Batas Fisik ===")
n_sebelum = len(df_clean)
for kolom, (batas_min, batas_max) in BATAS_FISIK.items():
    outlier  = ((df_clean[kolom] < batas_min) | (df_clean[kolom] > batas_max))
    n_outlier = outlier.sum()
    if n_outlier > 0:
        print(f"  {kolom:<25}: {n_outlier} nilai di luar [{batas_min}, {batas_max}]")
    df_clean[kolom] = df_clean[kolom].clip(batas_min, batas_max)
print(f"  → Semua nilai di-clamp ke batas fisik (tidak ada baris dihapus)")

# ── LAYER 2: IQR Capping ─────────────────────────────────────
# PERBAIKAN: Fitur non-negatif di-floor ke 0 agar batas bawah
# tidak turun ke negatif meskipun distribusinya right-skewed
FITUR_IQR_NON_NEGATIF = [
    'klorofil_a', 'tinggi_gelombang',
    'kecepatan_arus', 'hasil_tangkapan_kg'
]
FITUR_IQR_BEBAS = [
    'suhu_permukaan', 'salinitas'
]

print("\n=== LAYER 2: IQR Capping ===")
for kolom in FITUR_IQR_NON_NEGATIF + FITUR_IQR_BEBAS:
    Q1  = df_clean[kolom].quantile(0.25)
    Q3  = df_clean[kolom].quantile(0.75)
    IQR = Q3 - Q1
    batas_bawah = Q1 - 1.5 * IQR
    batas_atas  = Q3 + 1.5 * IQR

    # Floor batas bawah ke 0 untuk fitur non-negatif
    if kolom in FITUR_IQR_NON_NEGATIF:
        batas_bawah = max(batas_bawah, 0.0)

    n_outlier = ((df_clean[kolom] < batas_bawah) |
                 (df_clean[kolom] > batas_atas)).sum()
    df_clean[kolom] = df_clean[kolom].clip(batas_bawah, batas_atas)
    if n_outlier > 0:
        print(f"  {kolom:<25}: {n_outlier} outlier di-cap "
              f"[{batas_bawah:.2f}, {batas_atas:.2f}]")

# ── LAYER 3: Encode fitur siklikal ───────────────────────────
df_clean['fase_sin'] = np.sin(2 * np.pi * df_clean['fase_bulan'] / 4)
df_clean['fase_cos'] = np.cos(2 * np.pi * df_clean['fase_bulan'] / 4)
df_clean['jam_sin']  = np.sin(2 * np.pi * df_clean['jam_tangkap'] / 24)
df_clean['jam_cos']  = np.cos(2 * np.pi * df_clean['jam_tangkap'] / 24)
df_clean['arus_sin'] = np.sin(np.radians(df_clean['arah_arus']))
df_clean['arus_cos'] = np.cos(np.radians(df_clean['arah_arus']))

# ── LAYER 4: Split dulu, baru fit scaler ─────────────────────
# PERBAIKAN UTAMA: Scaler di-fit hanya pada train set
# hasil_tangkapan_kg tidak masuk FITUR — hanya basis label zona
FITUR = [
    'latitude', 'longitude',
    'jam_sin', 'jam_cos',
    'fase_sin', 'fase_cos',
    'suhu_permukaan', 'salinitas',
    'kecepatan_arus', 'arus_sin', 'arus_cos',
    'klorofil_a', 'tinggi_gelombang'
]

# Split awal — akan dipakai konsisten di Step 4 & 5
# zona belum ada di sini, stratify menyusul di Step 4 & 5
X_temp = df_clean[FITUR]
idx_train, idx_test = train_test_split(
    df_clean.index,
    test_size=0.2,
    random_state=42
)

# Fit scaler HANYA pada train
robust_scaler = RobustScaler()
robust_scaler.fit(df_clean.loc[idx_train, FITUR])
df_robust = robust_scaler.transform(df_clean[FITUR])

scaler = MinMaxScaler()
scaler.fit(df_robust[df_clean.index.isin(idx_train)])
df_clean[FITUR] = scaler.transform(df_robust)

print("\n=== Fitur setelah preprocessing (Robust + MinMax) ===")
print(df_clean[FITUR].describe().round(3))
print(f"\nTotal fitur: {len(FITUR)}")
print(f"hasil_tangkapan_kg : di-clean tapi tidak di-scale (basis label zona)")

print(f"\n=== Ringkasan ===")
print(f"  Data masuk   : {n_sebelum} baris")
print(f"  Data keluar  : {len(df_clean)} baris (tidak ada yang dihapus)")
print(f"  Train index  : {len(idx_train)} baris")
print(f"  Test index   : {len(idx_test)} baris")
print(f"  Metode       : Clamp fisik → IQR cap → Split → RobustScaler(train) → MinMaxScaler(train)")

# ============================================================
# CUMI-MAP | Step 3: K-Means Clustering (Robust) — FIXED
#
# Perbaikan:
# 1. Clustering menggunakan df_clean nilai ASLI (sebelum scaling Step 2)
#    bukan data yang sudah di-scale — centroid lebih interpretatif
# 2. Clip persentil 5-95 dihapus — hasil_tangkapan_kg sudah cukup
#    di-clean di Step 2 (clamp fisik + IQR), triple capping dihilangkan
# 3. K di-hardcode ke 3 — domain knowledge lebih kuat dari silhouette
#    silhouette tetap dihitung sebagai validasi, bukan penentu K
# 4. Validasi threshold diperbaiki — 68% Sedang sekarang terdeteksi
#    sebagai imbalance yang perlu diantisipasi di Step 4 & 5
# ============================================================

from sklearn.cluster import KMeans
from sklearn.metrics import silhouette_score
from sklearn.preprocessing import RobustScaler
import matplotlib.pyplot as plt

# ── Ambil nilai asli sebelum scaling untuk clustering ────────
# Clustering butuh nilai interpretatif (kg, mg/m³, °C)
# bukan nilai yang sudah di-transformasi dua kali
FITUR_CLUSTER = [
    'hasil_tangkapan_kg',  # basis utama zona
    'klorofil_a',
    'kecepatan_arus',
    'suhu_permukaan',
    'tinggi_gelombang',
]

# Ambil dari df_clean sebelum kolom FITUR di-scale
# hasil_tangkapan_kg sudah di-clean (clamp fisik + IQR) di Step 2
# tidak perlu clip lagi — triple capping dihilangkan
df_cluster = df_clean[FITUR_CLUSTER].copy()

# ── RobustScaler khusus clustering ───────────────────────────
robust_cluster   = RobustScaler()
X_cluster_scaled = robust_cluster.fit_transform(df_cluster)

# ── Validasi K=3 dengan silhouette — bukan penentu K ─────────
# K=3 dipilih berdasarkan domain: Rendah / Sedang / Tinggi
# Silhouette hanya untuk konfirmasi bahwa K=3 masuk akal
K_FINAL = 3

inertia    = []
sil_scores = []
K_range    = range(2, 9)

for k in K_range:
    km     = KMeans(n_clusters=k, random_state=42, n_init=10)
    labels = km.fit_predict(X_cluster_scaled)
    inertia.append(km.inertia_)
    sil_scores.append(silhouette_score(X_cluster_scaled, labels))

# Plot Elbow & Silhouette
fig, axes = plt.subplots(1, 2, figsize=(12, 4))
axes[0].plot(K_range, inertia, 'bo-', linewidth=2)
axes[0].axvline(K_FINAL, color='red', linestyle='--', alpha=0.6, label=f'K={K_FINAL} (dipilih)')
axes[0].set_xlabel('Jumlah Cluster (K)')
axes[0].set_ylabel('Inertia')
axes[0].set_title('Elbow Method')
axes[0].legend()
axes[0].grid(True, alpha=0.3)

axes[1].plot(K_range, sil_scores, 'ro-', linewidth=2)
axes[1].axvline(K_FINAL, color='navy', linestyle='--', alpha=0.6, label=f'K={K_FINAL} (dipilih)')
axes[1].set_xlabel('Jumlah Cluster (K)')
axes[1].set_ylabel('Silhouette Score')
axes[1].set_title('Silhouette Score')
axes[1].legend()
axes[1].grid(True, alpha=0.3)

sil_k3 = sil_scores[K_FINAL - 2]  # index 0 = K=2
print(f"\nSilhouette score K=3 : {sil_k3:.4f}")
print(f"Silhouette score terbaik (K={K_range[np.argmax(sil_scores)]}): {max(sil_scores):.4f}")
if sil_k3 >= 0.35:
    print(f"  ✓ K=3 dapat diterima secara statistik")
else:
    print(f"  ⚠️  Silhouette K=3 di bawah 0.35 — cluster kurang terpisah")

plt.suptitle('CUMI-MAP | Penentuan Jumlah Zona (K=3 dipilih)', fontweight='bold')
plt.tight_layout()
plt.show()

# ── Fit K-Means final dengan K=3 ─────────────────────────────
kmeans           = KMeans(n_clusters=K_FINAL, random_state=42, n_init=10)
df['zona']       = kmeans.fit_predict(X_cluster_scaled)
df_clean['zona'] = df['zona']

print(f"\n=== Distribusi zona ===")
print(df['zona'].value_counts().sort_index())

# ── Karakteristik zona ────────────────────────────────────────
zona_stats         = df.groupby('zona')['hasil_tangkapan_kg'].agg(['mean','count']).round(2)
zona_stats.columns = ['rata2_kg', 'jumlah_data']
zona_stats         = zona_stats.sort_values('rata2_kg', ascending=False)
print(f"\n=== Rata-rata hasil tangkapan per zona ===")
print(zona_stats)

# ── Validasi distribusi zona — threshold diperbaiki ──────────
# Threshold lama (10-90%) terlalu longgar — 68% Sedang lolos
# Threshold baru: warning jika satu kelas > 60% (imbalance nyata)
print(f"\n=== Validasi distribusi zona ===")
total      = len(df)
zona_sehat = True
catatan_imbalance = []

for zona_id, row in zona_stats.iterrows():
    pct = row['jumlah_data'] / total * 100
    if pct > 60:
        status = '⚠️  DOMINAN — antisipasi class_weight di Step 4 & 5'
        zona_sehat = False
        catatan_imbalance.append(zona_id)
    elif pct < 10:
        status = '⚠️  TERLALU KECIL — pertimbangkan oversampling'
        zona_sehat = False
    else:
        status = '✓'
    print(f"  Zona {zona_id}: {int(row['jumlah_data'])} data ({pct:.1f}%) {status}")

if not zona_sehat:
    print(f"\n  ⚠️  Distribusi tidak seimbang — class_weight='balanced' WAJIB dipakai di Step 4 & 5")
else:
    print(f"\n  ✓ Distribusi zona seimbang.")

# ── Label zona (K=3 pasti Tinggi/Sedang/Rendah) ──────────────
zona_sorted = zona_stats.index.tolist()  # urutan: tertinggi → terendah tangkapan
label_map   = {
    zona_sorted[0]: 'Tinggi',
    zona_sorted[1]: 'Sedang',
    zona_sorted[2]: 'Rendah',
}

df['zona_label']       = df['zona'].map(label_map)
df_clean['zona_label'] = df['zona_label']

print(f"\n=== Label zona ===")
print(df[['zona','zona_label']].drop_duplicates().sort_values('zona'))

# ── Visualisasi sebaran zona ──────────────────────────────────
plt.figure(figsize=(8, 6))
colors    = {'Tinggi': '#e74c3c', 'Sedang': '#f39c12', 'Rendah': '#2ecc71'}
for label, group in df.groupby('zona_label'):
    plt.scatter(group['longitude'], group['latitude'],
                c=colors[label],
                label=f'Zona {label}',
                alpha=0.6, s=30)
plt.xlabel('Longitude')
plt.ylabel('Latitude')
plt.title('CUMI-MAP | Sebaran Zona Penangkapan (K-Means, K=3)')
plt.legend()
plt.grid(True, alpha=0.3)
plt.tight_layout()
plt.show()

# ============================================================
# CUMI-MAP | Step 4: Decision Tree — Analisis Fitur Penting
# FIXED
#
# Perbaikan:
# 1. Gunakan idx_train/idx_test dari Step 2 — tidak ada split ulang
# 2. Validasi threshold disesuaikan dengan Step 3 (>60% = dominan)
# 3. Threshold seleksi fitur diganti dari median ke importance > 0.05
#    agar fitur noise (importance < 0.01) tidak ikut terbawa
# 4. max_depth dicari via loop — tidak di-hardcode ke 8
# 5. FITUR_EXPECTED dihapus — validasi hardcode tidak bermakna
# 6. CV menggunakan index train saja — tidak bocor ke test
# ============================================================

from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import cross_val_score
from sklearn.metrics import classification_report, accuracy_score, recall_score
import matplotlib.pyplot as plt
import pandas as pd

# ── Validasi input dari Step 3 ───────────────────────────────
# Threshold disesuaikan: >60% = dominan (konsisten dengan Step 3)
print("=== Validasi input dari Step 3 ===")
zona_dist = df_clean['zona_label'].value_counts()
total     = len(df_clean)
ada_dominan = False
for zona, count in zona_dist.items():
    pct = count / total * 100
    if pct > 60:
        status = '⚠️ DOMINAN'
        ada_dominan = True
    elif pct < 10:
        status = '⚠️ TERLALU KECIL'
    else:
        status = '✓'
    print(f"  {zona}: {count} data ({pct:.1f}%) {status}")

if ada_dominan:
    print("\n  ⚠️ Ada zona dominan — class_weight='balanced' WAJIB dipakai.")
    print("     Lanjut training dengan balanced weight.")
else:
    print("\n  ✓ Distribusi zona sehat. Lanjut ke Decision Tree.")

# ── Gunakan idx_train/idx_test dari Step 2 ───────────────────
# Tidak ada train_test_split ulang — konsisten dengan scaler
X = df_clean[FITUR]
y = df_clean['zona']

X_train = X.loc[idx_train]
X_test  = X.loc[idx_test]
y_train = y.loc[idx_train]
y_test  = y.loc[idx_test]

print(f"\n=== Distribusi split ===")
print(f"  Train: {len(X_train)} | Test: {len(X_test)}")
print(f"\n  Distribusi zona di train:")
for zona_id, count in y_train.value_counts().sort_index().items():
    print(f"    Zona {label_map[zona_id]}: {count} ({count/len(y_train)*100:.1f}%)")
print(f"\n  Distribusi zona di test:")
for zona_id, count in y_test.value_counts().sort_index().items():
    print(f"    Zona {label_map[zona_id]}: {count} ({count/len(y_test)*100:.1f}%)")

# ── Cari max_depth optimal via loop ──────────────────────────
# Tidak di-hardcode — pilih depth dengan CV accuracy tertinggi
# CV hanya pada train set agar test set tidak bocor
print(f"\n=== Pencarian max_depth optimal ===")
depth_scores = {}
for depth in range(3, 12):
    dt_tmp = DecisionTreeClassifier(
        max_depth=depth,
        random_state=42,
        class_weight='balanced'
    )
    cv = cross_val_score(dt_tmp, X_train, y_train, cv=5, scoring='accuracy')
    depth_scores[depth] = cv.mean()
    print(f"  depth={depth}: CV accuracy = {cv.mean()*100:.2f}% ± {cv.std()*100:.2f}%")

best_depth = max(depth_scores, key=depth_scores.get)
print(f"\n  → max_depth optimal: {best_depth} (CV accuracy: {depth_scores[best_depth]*100:.2f}%)")

# ── Training Decision Tree ────────────────────────────────────
dt = DecisionTreeClassifier(
    max_depth=best_depth,
    random_state=42,
    class_weight='balanced'
)
dt.fit(X_train, y_train)
y_pred_dt = dt.predict(X_test)
akurasi   = accuracy_score(y_test, y_pred_dt)

# ── CV final pada train set saja ─────────────────────────────
cv_scores = cross_val_score(dt, X_train, y_train, cv=5, scoring='accuracy')
print(f"\n=== Decision Tree (max_depth={best_depth}) ===")
print(f"  Akurasi test set  : {akurasi*100:.2f}%")
print(f"  Cross-Val (5-fold): {cv_scores.mean()*100:.2f}% ± {cv_scores.std()*100:.2f}%")

# ── Classification report ────────────────────────────────────
nama_zona = [label_map[i] for i in sorted(label_map.keys())]
print(f"\n--- Classification Report ---")
print(classification_report(y_test, y_pred_dt, target_names=nama_zona))

# ── Deteksi false accuracy ───────────────────────────────────
print("=== Deteksi False Accuracy ===")
recalls   = recall_score(y_test, y_pred_dt, average=None)
false_acc = False
for zona_id, recall in zip(sorted(label_map.keys()), recalls):
    zona_nama = label_map[zona_id]
    status    = '✓' if recall >= 0.60 else '⚠️ RECALL RENDAH'
    print(f"  Recall Zona {zona_nama}: {recall*100:.1f}% {status}")
    if recall < 0.60:
        false_acc = True

if false_acc:
    print(f"\n  ⚠️ Model kemungkinan mengalami false accuracy.")
else:
    print(f"\n  ✓ Recall semua zona sehat. Akurasi dapat dipercaya.")

# ── Feature Importance ───────────────────────────────────────
importances = pd.Series(
    dt.feature_importances_, index=FITUR
).sort_values(ascending=True)

plt.figure(figsize=(8, 6))
# Threshold 0.05 — fitur dengan importance < 0.05 dianggap noise
THRESHOLD_IMPORTANCE = 0.05
colors_bar = ['#e74c3c' if v >= THRESHOLD_IMPORTANCE
              else '#95a5a6' for v in importances]
importances.plot(kind='barh', color=colors_bar)
plt.axvline(THRESHOLD_IMPORTANCE, color='navy',
            linestyle='--', alpha=0.5,
            label=f'Threshold ({THRESHOLD_IMPORTANCE})')
plt.xlabel('Feature Importance')
plt.title(f'CUMI-MAP | Feature Importance (Decision Tree, depth={best_depth})')
plt.legend()
plt.tight_layout()
plt.show()

# ── Seleksi fitur dengan threshold 0.05 ──────────────────────
# Median threshold dihapus — terlalu arbitrary
# 0.05 memastikan fitur noise (< 0.01) tidak ikut ke RF
FITUR_PENTING = importances[
    importances >= THRESHOLD_IMPORTANCE
].index.tolist()

print(f"\n=== Fitur terpilih untuk Random Forest ===")
print(f"  Threshold importance : {THRESHOLD_IMPORTANCE}")
for f in FITUR_PENTING:
    print(f"  ✓ {f}: {importances[f]:.4f}")

# Fitur yang dibuang
fitur_dibuang = importances[importances < THRESHOLD_IMPORTANCE].index.tolist()
if fitur_dibuang:
    print(f"\n  Fitur dibuang (importance < {THRESHOLD_IMPORTANCE}):")
    for f in fitur_dibuang:
        print(f"  ✗ {f}: {importances[f]:.4f}")

# ============================================================
# CUMI-MAP | Step 5: Random Forest — Training & Evaluasi
# FIXED
#
# Perbaikan:
# 1. Hapus train_test_split ulang — pakai idx_train/idx_test dari Step 2
# 2. Tambah class_weight='balanced' — konsisten dengan Step 4
# 3. CV dilakukan pada X_train saja — tidak bocor ke test set
# 4. Simpan robust_scaler — pipeline inference lengkap
# 5. Tambah confusion matrix per kelas lengkap dengan label benar
# ============================================================

from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import (accuracy_score, classification_report,
                             confusion_matrix, ConfusionMatrixDisplay,
                             recall_score)
from sklearn.model_selection import cross_val_score
import matplotlib.pyplot as plt
import pandas as pd
import joblib

# ── Gunakan idx_train/idx_test dari Step 2 ───────────────────
# Tidak ada split ulang — konsisten dengan scaler
X_rf = df_clean[FITUR_PENTING]
y_rf = df_clean['zona']

X_train_rf = X_rf.loc[idx_train]
X_test_rf  = X_rf.loc[idx_test]
y_train_rf = y_rf.loc[idx_train]
y_test_rf  = y_rf.loc[idx_test]

print("=== Distribusi split (dari Step 2) ===")
print(f"  Train : {len(X_train_rf)} baris")
print(f"  Test  : {len(X_test_rf)} baris")
print(f"\n  Distribusi zona di train:")
for zona_id, count in y_train_rf.value_counts().sort_index().items():
    print(f"    Zona {label_map[zona_id]}: {count} ({count/len(y_train_rf)*100:.1f}%)")
print(f"\n  Distribusi zona di test:")
for zona_id, count in y_test_rf.value_counts().sort_index().items():
    print(f"    Zona {label_map[zona_id]}: {count} ({count/len(y_test_rf)*100:.1f}%)")

# ── Training Random Forest ────────────────────────────────────
# class_weight='balanced' — konsisten dengan Decision Tree Step 4
# mengingat Sedang 68% dominan
rf = RandomForestClassifier(
    n_estimators=200,
    max_depth=10,
    min_samples_split=5,
    min_samples_leaf=2,
    class_weight='balanced',
    random_state=42,
    n_jobs=-1
)
rf.fit(X_train_rf, y_train_rf)

# ── Prediksi & Evaluasi ───────────────────────────────────────
y_pred_rf = rf.predict(X_test_rf)
akurasi   = accuracy_score(y_test_rf, y_pred_rf)

# ── CV pada train set saja ────────────────────────────────────
# Tidak pakai X_rf penuh — test set tidak boleh ikut CV
cv_scores = cross_val_score(rf, X_train_rf, y_train_rf, cv=5, scoring='accuracy')

print("\n" + "=" * 50)
print("  CUMI-MAP | Hasil Evaluasi Random Forest")
print("=" * 50)
print(f"  Akurasi Test Set   : {akurasi*100:.2f}%")
print(f"  Cross-Val (5-fold) : {cv_scores.mean()*100:.2f}% ± {cv_scores.std()*100:.2f}%")
gap = abs(akurasi - cv_scores.mean())
print(f"  Gap CV vs Test     : {gap*100:.2f}%", end=" ")
print("✓ Stabil" if gap < 0.05 else "⚠️ Gap besar — periksa overfit")
print("=" * 50)

# ── Classification Report ─────────────────────────────────────
nama_zona = [label_map[i] for i in sorted(label_map.keys())]
print(f"\n--- Classification Report ---")
print(classification_report(
    y_test_rf, y_pred_rf,
    target_names=[f"Zona {label_map[i]}" for i in sorted(label_map.keys())]
))

# ── Deteksi False Accuracy ────────────────────────────────────
print("=== Deteksi False Accuracy ===")
recalls   = recall_score(y_test_rf, y_pred_rf, average=None)
false_acc = False
for zona_id, recall in zip(sorted(label_map.keys()), recalls):
    zona_nama = label_map[zona_id]
    status    = '✓' if recall >= 0.60 else '⚠️ RECALL RENDAH'
    print(f"  Recall Zona {zona_nama}: {recall*100:.1f}% {status}")
    if recall < 0.60:
        false_acc = True

if false_acc:
    print(f"\n  ⚠️ Model kemungkinan mengalami false accuracy.")
else:
    print(f"\n  ✓ Recall semua zona sehat. Akurasi dapat dipercaya.")

# ── Confusion Matrix ──────────────────────────────────────────
fig, ax = plt.subplots(figsize=(7, 5))
cm   = confusion_matrix(y_test_rf, y_pred_rf)
disp = ConfusionMatrixDisplay(
    cm,
    display_labels=[f"Zona {label_map[i]}" for i in sorted(label_map.keys())]
)
disp.plot(ax=ax, colorbar=False, cmap='Blues')
ax.set_title('CUMI-MAP | Confusion Matrix (Random Forest)')
plt.tight_layout()
plt.show()

# ── Feature Importance RF ─────────────────────────────────────
rf_importance = pd.Series(
    rf.feature_importances_, index=FITUR_PENTING
).sort_values(ascending=True)

plt.figure(figsize=(8, 5))
rf_importance.plot(kind='barh', color='#2980b9')
plt.axvline(0.05, color='red', linestyle='--',
            alpha=0.5, label='Threshold (0.05)')
plt.xlabel('Feature Importance')
plt.title('CUMI-MAP | Feature Importance (Random Forest)')
plt.legend()
plt.tight_layout()
plt.show()

print("\n=== Feature Importance (Random Forest) ===")
for f, v in rf_importance.sort_values(ascending=False).items():
    print(f"  {f:<20}: {v:.4f}")

# ── Simpan semua artefak pipeline ────────────────────────────
# PERBAIKAN: robust_scaler ikut disimpan — pipeline inference lengkap
# Urutan transform: robust_scaler → scaler → rf.predict
joblib.dump(rf,            'cumimap_rf_model.pkl')
joblib.dump(robust_scaler, 'cumimap_robust_scaler.pkl')
joblib.dump(scaler,        'cumimap_scaler.pkl')
joblib.dump(kmeans,        'cumimap_kmeans.pkl')

print("\n✓ Model tersimpan    : cumimap_rf_model.pkl")
print("✓ RobustScaler       : cumimap_robust_scaler.pkl")
print("✓ MinMaxScaler       : cumimap_scaler.pkl")
print("✓ KMeans tersimpan   : cumimap_kmeans.pkl")
print("\n— Urutan inference —")
print("  Input → robust_scaler.transform → scaler.transform → rf.predict")

# ============================================================
# CUMI-MAP | Step 6: Export CSV — Hasil Prediksi & Evaluasi
# FIXED
#
# Perbaikan:
# 1. Ringkasan akurasi mencakup semua zona termasuk Rendah
# 2. prediksi_benar menggunakan dtype bool eksplisit — bukan object
# 3. overall akurasi dihitung dari perbandingan langsung,
#    bukan .mean() pada kolom object
# 4. Ringkasan berbasis zona_label aktual bukan prediksi
#    agar tidak misleading saat ada misclassifikasi
# ============================================================

import pandas as pd
from google.colab import files

# ── Prediksi seluruh data ─────────────────────────────────────
# X_all dari df_clean yang sudah di-scale Step 2
# nilai fitur di df_export tetap nilai mentah untuk keterbacaan
df_export = df.copy()

X_all     = df_clean[FITUR_PENTING]
proba_all = rf.predict_proba(X_all)

df_export['zona_prediksi']       = rf.predict(X_all)
df_export['zona_prediksi_label'] = df_export['zona_prediksi'].map(label_map)

# Ambil probabilitas per kelas dengan lookup eksplisit
idx_tinggi = list(rf.classes_).index(
    [k for k, v in label_map.items() if v == 'Tinggi'][0]
)
idx_sedang = list(rf.classes_).index(
    [k for k, v in label_map.items() if v == 'Sedang'][0]
)
idx_rendah = list(rf.classes_).index(
    [k for k, v in label_map.items() if v == 'Rendah'][0]
)

df_export['prob_zona_tinggi'] = proba_all[:, idx_tinggi].round(4)
df_export['prob_zona_sedang'] = proba_all[:, idx_sedang].round(4)
df_export['prob_zona_rendah'] = proba_all[:, idx_rendah].round(4)

# ── Tandai split ──────────────────────────────────────────────
# Gunakan idx_test dari Step 2 — konsisten dengan evaluasi
df_export['split'] = df_export.index.map(
    lambda i: 'test' if i in idx_test else 'train'
)

# ── Tandai prediksi benar/salah ───────────────────────────────
# PERBAIKAN: dtype bool eksplisit — bukan None/True/False campuran
# NaN untuk train, bool untuk test
test_mask = df_export['split'] == 'test'
df_export['prediksi_benar'] = pd.NA  # NA bukan None — tipe konsisten
df_export.loc[test_mask, 'prediksi_benar'] = (
    df_export.loc[test_mask, 'zona'].astype(int) ==
    df_export.loc[test_mask, 'zona_prediksi'].astype(int)
)

# ── Susun kolom output ────────────────────────────────────────
df_export = df_export[[
    'latitude', 'longitude',
    'jam_tangkap', 'fase_bulan',
    'suhu_permukaan', 'salinitas',
    'kecepatan_arus', 'arah_arus',
    'klorofil_a', 'tinggi_gelombang',
    'hasil_tangkapan_kg',
    'zona', 'zona_label',
    'zona_prediksi', 'zona_prediksi_label',
    'prob_zona_tinggi', 'prob_zona_sedang', 'prob_zona_rendah',
    'split', 'prediksi_benar'
]]

df_export.to_csv('cumimap_hasil_prediksi.csv', index=False)
print("✓ CSV tersimpan: cumimap_hasil_prediksi.csv")
print(f"  Total baris  : {len(df_export)}")
print(f"  Total kolom  : {len(df_export.columns)}")

# ── Ringkasan akurasi per zona ────────────────────────────────
# PERBAIKAN 1: mencakup semua zona termasuk Rendah
# PERBAIKAN 2: berbasis zona_label AKTUAL bukan prediksi
#              agar misklasifikasi tidak tersembunyi
print("\n=== Ringkasan Akurasi per Zona (Test Set) ===")
test_df   = df_export[df_export['split'] == 'test'].copy()
total_tes = len(test_df)

for label in ['Tinggi', 'Sedang', 'Rendah']:
    # Subset berdasarkan zona AKTUAL
    subset = test_df[test_df['zona_label'] == label]
    if len(subset) == 0:
        print(f"  Zona {label}: tidak ada data di test set")
        continue
    benar = subset['prediksi_benar'].sum()
    total = len(subset)
    print(f"  Zona {label:<6}: {int(benar)}/{total} benar "
          f"({benar/total*100:.1f}%)")

# ── Overall akurasi — dihitung langsung dari bool ─────────────
# PERBAIKAN 3: tidak pakai .mean() pada kolom object
n_benar  = int(test_df['prediksi_benar'].sum())
n_total  = int(test_df['prediksi_benar'].notna().sum())
akurasi_final = n_benar / n_total

print(f"\n  Overall akurasi test : {n_benar}/{n_total} "
      f"({akurasi_final*100:.2f}%)")

# Konsistensi dengan Step 5
print(f"\n=== Konsistensi dengan Step 5 ===")
from sklearn.metrics import accuracy_score
akurasi_step5 = accuracy_score(y_test_rf, y_pred_rf)
selisih = abs(akurasi_final - akurasi_step5)
print(f"  Akurasi Step 5 : {akurasi_step5*100:.2f}%")
print(f"  Akurasi Step 6 : {akurasi_final*100:.2f}%")
if selisih < 0.001:
    print(f"  ✓ Konsisten — selisih {selisih*100:.3f}%")
else:
    print(f"  ⚠️ Tidak konsisten — selisih {selisih*100:.3f}%, periksa index")

# ── Preview test set ──────────────────────────────────────────
print("\n=== Preview 5 baris (test set) ===")
print(test_df[[
    'latitude', 'longitude',
    'klorofil_a', 'suhu_permukaan',
    'hasil_tangkapan_kg', 'zona_label',
    'zona_prediksi_label',
    'prob_zona_tinggi', 'prediksi_benar'
]].head().to_string())

# ── Download ──────────────────────────────────────────────────
files.download('cumimap_hasil_prediksi.csv')